name: Continuous Integration

on: [push, pull_request]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.{js,jsx,ts,tsx,json,yaml,yml,html,css,less,scss,md,markdown,mdx,graphql,mdx,py,java,go}
